version: '3.9'

services:
  boilerplate-node-auth-mongodb:
    container_name: ${MONGO_DB_NAME}
    image: mongo:7.0
    volumes:
      - ./mongodb/data/db:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: ['--auth']
    ports:
      - 27017:27017

  
  